### ISSUE TITLE
Wrong Query Positioning

### ISSUE THREAD

**Issue by zimt28** [Sansui233/logseq-bonofix-theme#10]
Hi, thanks for the nice theme!
There's an issue with queries (both simple and advanced), their position is a little off:
<img width="394" alt="Screenshot 2022-03-10 at 10 52 47" src="https://user-images.githubusercontent.com/1764689/157636954-c7ee423b-7855-4982-a222-9bed3c934e2a.png">

**Comment by Sansui233** [comment]
The shift makes raw texts to be editable. If it's horizontally aligned, clicking query only makes it collapse instead of editing raw texts. Default theme leaves a bigger gap in query and code block to ensure they can be clicked to edit in raw texts.

I didn't come up with a good idea to make it totally aligned without editing issue. The best solution should be an edit button in these blocks. Pure css is not able to achieve the task. If you have any good idea please consider contributing~
